### PR TITLE
Add dependencies for Minecraft

### PR DESCRIPTION
**Pull request by vchernin**
Required for https://github.com/flathub/com.mojang.Minecraft/pull/112
Necessary if other package doesn't happen to be bundling these already

### CODE REVIEW

**Comment by xinyazhang** [comment]
I'm happy to merge them to support Minecraft flatpak, but there is a question left: how do these two flatpak packages interactive?
In other words. If this got merged, how can users invoke flatpaked Minecraft with this version of gamescope? (Note this gamescope was not designed to use without Steam)
Consider the containerized nature of flatpak I do not think we can do this without hacking, and the end effect is we bundled two more libraries (always remember bundling is a security nightmare) without benefits.

**Comment by vchernin** [comment]
https://github.com/flathub/com.mojang.Minecraft/pull/112 describes the changes needed to make it work.

Basically I made it that if you have this extension installed, and create `~/.var/app/com.mojang.Minecraft/.minecraft/gamescope.txt`, it runs Minecraft in Gamescope.

> Consider the containerized nature of flatpak I do not think we can do this without hacking, and the end effect is we bundled two more libraries (always remember bundling is a security nightmare) without benefits.

The benefit is apps like minecraft can use it without bundling extra dependencies themselves. If steam did not happens to bundle those dependencies already Gamescope wouldn't work there I think.

I don't necessarily think this is ideal, but I don't know of a better way.

For security perhaps x-checker-data would be good to keep things updated here. Interested in automatic PRs for module updates?

**Comment by xinyazhang** [comment]
Okay I see how it works.

**Comment by gasinvein** [comment]
I suspect this won't be enough. You need to make sure that gamescope and/or its dependencies are linked with bundled libmd/libbsd, and, additionally, either set `RPATH` for binaries or link with libmd/libbsd statically.

**Pull request merged**
