### PR TITLE
Prepare for migration

### PR DESCRIPTION
**Pull request by orowith2os**
https://github.com/flathub/flathub/pull/4329

### CODE REVIEW

**Comment by travier** [comment]
Mixed feelings here. Let's make sure the standalone extension works well before doing the full migration.

**Comment by xinyazhang** [comment]
Ping me if the test is successful so I'll merge it.

**Comment by TheEvilSkeleton** [comment]
The info works for me :+1: 

```
Info: (pinned) runtime com.valvesoftware.Steam.Utility.gamescope branch test is end-of-life, with reason:
   The gamescope Flatpak has been migrated to org.freedesktop.Platform.VulkanLayer.gamescope.

```

**Comment by TheEvilSkeleton** [comment]
Oh crud, I wasn't clear but I only tested the info, not Gamescope itself :sweat_smile:

**Comment by orowith2os** [comment]
We've still got 3 hours to test it before any final binaries are shipped to users, it's not too big of a deal. A PR reverting the commit can be made if necessary.

**Comment by TheEvilSkeleton** [comment]
Okay, I added `gamescope -h 1080 -H 1440 -e -- %command%` in the launch option for Satisfactory. It works on the old runtime extension but not on the new one. I added `/usr/lib/extensions/vulkan/gamescope/bin` to PATH and tested if the `gamescope` command was available.

**Comment by TheEvilSkeleton** [comment]
<details><summary>Error message</summary>
<p>

```
System startup time: 14.57 seconds
BuildCompleteAppOverviewChange: 217 apps
RegisterForAppOverview 1: 19ms
RegisterForAppOverview 2: 19ms
ExecCommandLine: "'/var/home/TheEvilSkeleton/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam' '-no-cef-sandbox'"
CAPIJobRequestUserStats - Server response failed 2
GameAction [AppID 526870, ActionID 1] : LaunchApp changed task to ProcessingInstallScript with ""
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
GameAction [AppID 526870, ActionID 1] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 526870, ActionID 1] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 526870, ActionID 1] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 526870, ActionID 1] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 526870, ActionID 1] : LaunchApp continues with user response "CreatingProcess"
/bin/sh\0-c\0gamescope -h 1080 -H 1440 -e -- /var/home/TheEvilSkeleton/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=526870 -- /var/home/TheEvilSkeleton/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/app/share/steam/compatibilitytools.d/Proton-GE'/proton waitforexitandrun  '/run/media/TheEvilSkeleton/DATA/Steam Games/steamapps/common/Satisfactory/FactoryGame.exe' -NO_EOS_OVERLAY\0
Game process added : AppID 526870 "gamescope -h 1080 -H 1440 -e -- /var/home/TheEvilSkeleton/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=526870 -- /var/home/TheEvilSkeleton/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/app/share/steam/compatibilitytools.d/Proton-GE'/proton waitforexitandrun  '/run/media/TheEvilSkeleton/DATA/Steam Games/steamapps/common/Satisfactory/FactoryGame.exe' -NO_EOS_OVERLAY", ProcID 1592, IP 0.0.0.0:0
chdir "/run/media/TheEvilSkeleton/DATA/Steam Games/steamapps/common/Satisfactory"
ERROR: ld.so: object '/var/home/TheEvilSkeleton/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/var/home/TheEvilSkeleton/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
wlserver: [backend/headless/backend.c:68] Creating headless backend
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
GameAction [AppID 526870, ActionID 1] : LaunchApp changed task to WaitingGameWindow with ""
GameAction [AppID 526870, ActionID 1] : LaunchApp changed task to Completed with ""
WARNING: discarding _NET_WM_PID 5 as invalid for X11 window - use specialized XCB_X11_TO_PID function!
vulkan: selecting physical device 'AMD Radeon RX 580 Series (RADV POLARIS10)': queue family 1
vulkan: physical device does not support DRM format modifiers
Fossilize INFO: Overriding serialization path: "/run/media/TheEvilSkeleton/DATA/Steam Games/steamapps/shadercache/526870/fozpipelinesv6/steamapprun_pipeline_cache".
vulkan: supported DRM formats for sampling usage:
vulkan:   0x34325241
vulkan:   0x34325258
vulkan:   0x3231564E
wlserver: Running compositor on wayland display 'gamescope-0'
wlserver: [backend/headless/backend.c:16] Starting headless backend
wlserver: [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X0: Address already in use
wlserver: [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X1: Address already in use
wlserver: [xwayland/server.c:108] Starting Xwayland on :2
ERROR: ld.so: object '/var/home/TheEvilSkeleton/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Xwayland: error while loading shared libraries: libXfont2.so.2: cannot open shared object file: No such file or directory
wlserver: [xwayland/server.c:270] Xwayland startup failed, not setting up xwm
[2023-07-17 17:40:14] Background update loop checking for update. . .
[2023-07-17 17:40:14] Checking for available updates...
[2023-07-17 17:40:14] Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_ubuntu12?t=887761387
[2023-07-17 17:40:14] Manifest download: send request
[2023-07-17 17:40:14] Manifest download: waiting for download to finish
[2023-07-17 17:40:15] Manifest download: finished
[2023-07-17 17:40:15] Download skipped: /steam_client_ubuntu12?t=887761387 version 1689034492, installed version 1689034492, existing pending version 0
[2023-07-17 17:40:15] Nothing to do
Game process removed: AppID 526870 "gamescope -h 1080 -H 1440 -e -- /var/home/TheEvilSkeleton/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=526870 -- /var/home/TheEvilSkeleton/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/app/share/steam/compatibilitytools.d/Proton-GE'/proton waitforexitandrun  '/run/media/TheEvilSkeleton/DATA/Steam Games/steamapps/common/Satisfactory/FactoryGame.exe' -NO_EOS_OVERLAY", ProcID 1592 
Uploaded AppInterfaceStats to Steam

```

</p>
</details>

**Comment by orowith2os** [comment]
Should be fixed by https://github.com/flathub/org.freedesktop.Platform.VulkanLayer.gamescope/pull/1

**Pull request merged**
