### PR TITLE
Update to gamescope 3.9.2

### PR DESCRIPTION
**Pull request by doraskayo**
Also update all of its dependencies while at it:
* freedesktop-sdk: `21.08`
* xwayland: `21.1.2`
* libinput: `1.19.0`
* libtirpc: `1.3.2`
* xfont2: `2.0.5`
* fontutil: `1.3.2`
* tirpc: `1.3.2`

### CODE REVIEW

**Comment by doraskayo** [comment]
Marked as draft until tested.

**Comment by doraskayo** [comment]
The build fails because of the issue described here: https://github.com/Plagman/gamescope/issues/61#issuecomment-921941473. I don't have a solution for this yet.

**Comment by xinyazhang** [comment]
@doraskayo (For the record) `libinput` version was intentionally chosen because at that time any newer version won't compile.
However, since the bot has successfully built the package I'm going to merge this request.

**Comment by doraskayo** [comment]
@xinyazhang, I tested it and it indeed worked. Thanks for merging.

**Comment by eli-schwartz** [comment]
> Since gamescope's buildsystem actually depends on it appearing like a Meson project, we must make sure it remains such, so we manually copy the content of the subprojects/packagefiles/stb directory to its subproject source directory.

In the next version of meson, this should no longer be necessary and you should be able to clone the stb repo into place with `dest:` and then `meson subprojects update --reset` will work rather than failing with a network error.

You'll then be able to remove the part where you poke around in meson internal implementation details of the packagefiles/ directory. :)

See https://github.com/mesonbuild/meson/pull/9277

**Pull request merged**
